const WHATSAPP="5500000000000"; // TROQUE pelo número da pizzaria: 55 + DDD + número, somente dígitos
const salgadas=[
["Caipira","Frango, milho, catupiry, azeitona"],["Frango Catupiry","Frango, catupiry, azeitona"],["Francesa","Presunto, mussarela, ovo, milho, cebola"],["Milho Verde","Mussarela, milho"],["Mista (Queijo e Presunto)","Mussarela, presunto"],["Napolitana","Mussarela, frango, milho, ervilha"],["3 Queijos","Mussarela, parmesão, queijo coalho"],["Atum","Mussarela, atum"],["Calabresa","Mussarela, calabresa, cebola, azeitona"],["Portuguesa","Mussarela, presunto, ovos, azeitona, cebola"],["Carne Seca","Mussarela, carne seca, cebola, tomate"],["Nordestina","Mussarela, milho verde, cebola, calabresa ralada"],["Moda da Casa","Mussarela, presunto, calabresa, tomate, pimentão"]];
const doces=[["Romeu e Julieta","Leite condensado, mussarela, goiabada"],["Banana","Leite condensado, mussarela, banana, canela"],["Brigadeiro","Leite condensado, mussarela, chocolate"]];
const prices={Pequena:20,Média:30,Grande:40}; let cart=[]; let custom={size:"Pequena",sauce:"Tomate",base:"Mussarela",extras:[]};

function money(v){return "R$ "+v.toFixed(2).replace(".",",")}
function render(list,id){document.getElementById(id).innerHTML=list.map((p,i)=>`<article class="pizza"><div><h3>${i+1}. ${p[0]}</h3><p>${p[1]}</p></div><div class="sizes">${Object.entries(prices).map(([s,v])=>`<button onclick="addPizza('${p[0]}','${s}',${v})">${s}<br>${money(v)}</button>`).join("")}</div></article>`).join("")}
function addPizza(name,size,price){cart.push({name:`${name} — ${size}`,price});updateCart();alert("Pizza adicionada ao pedido!")}
function updateCart(){document.getElementById("cartCount").textContent=cart.length;document.getElementById("cartItems").innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-item"><b>${x.name}</b><br>${money(x.price)} <button onclick="removeItem(${i})">✕</button></div>`).join(""):"<p>Seu pedido está vazio.</p>";document.getElementById("cartTotal").textContent=money(cart.reduce((a,b)=>a+b.price,0))}
function removeItem(i){cart.splice(i,1);updateCart()}
function abrirCarrinho(){document.getElementById("cart").classList.remove("hidden");document.getElementById("overlay").classList.remove("hidden")}
function fecharCarrinho(){document.getElementById("cart").classList.add("hidden");document.getElementById("overlay").classList.add("hidden")}
function pedirWhatsApp(){window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent("Olá! Gostaria de fazer um pedido pelo cardápio da Vem K'Sabor.")}`,"_blank")}
function finalizarPedido(){if(!cart.length)return alert("Adicione pelo menos uma pizza.");let n=document.getElementById("customerName").value||"Cliente";let a=document.getElementById("customerAddress").value||"Vou informar o endereço pelo WhatsApp";let itens=cart.map(x=>`• ${x.name} — ${money(x.price)}`).join("\n");let total=money(cart.reduce((s,x)=>s+x.price,0));let msg=`Olá, sou ${n} e gostaria de fazer este pedido:\n${itens}\nTotal: ${total}\nEndereço: ${a}`;window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(msg)}`,"_blank")}
function setupBuilder(){document.getElementById("sizes").innerHTML=Object.keys(prices).map(s=>`<button class="${s==="Pequena"?"active":""}" onclick="choose('size','${s}',this)">${s}<br>${money(prices[s])}</button>`).join("");document.getElementById("sauces").innerHTML=["Tomate","Branco (Catupiry)"].map(s=>`<button class="${s==="Tomate"?"active":""}" onclick="choose('sauce','${s}',this)">${s}</button>`).join("");document.getElementById("bases").innerHTML=["Mussarela","Provolone","Parmesão"].map(s=>`<button class="${s==="Mussarela"?"active":""}" onclick="choose('base','${s}',this)">${s}</button>`).join("");let ex=["Calabresa","Frango","Catupiry","Presunto","Milho","Ervilha","Carne Seca","Azeitona","Ovo","Cebola","Tomate","Pimentão"];document.getElementById("extras").innerHTML=ex.map(e=>`<label><input type="checkbox" value="${e}" onchange="toggleExtra(this)"> ${e}</label>`).join("")}
function choose(k,v,el){custom[k]=v;el.parentElement.querySelectorAll("button").forEach(x=>x.classList.remove("active"));el.classList.add("active");calcCustom()}
function toggleExtra(el){if(el.checked)custom.extras.push(el.value);else custom.extras=custom.extras.filter(x=>x!==el.value);calcCustom()}
function calcCustom(){document.getElementById("builderTotal").textContent=money(prices[custom.size]+custom.extras.length*5)}
function addCustom(){let p=prices[custom.size]+custom.extras.length*5;cart.push({name:`Pizza personalizada — ${custom.size} — ${custom.sauce} — ${custom.base}${custom.extras.length?" — "+custom.extras.join(", "):""}`,price:p});updateCart();abrirCarrinho()}
function renderStamps(){let n=Number(localStorage.getItem("vk_points")||0);document.getElementById("stamps").innerHTML=[1,2,3,4,5,6].map(i=>`<div class="stamp ${i===6?"free":""}">${i<=n?i:"○"}</div>`).join("")}
render(salgadas,"salgadasGrid");render(doces,"docesGrid");setupBuilder();renderStamps();updateCart();
